const caseStudies = [
  {
    id: 'sales-inventory-assistant',
    title: 'Sales Assistant and Inventory Control Mobile App',
    titleEs: 'Aplicación Móvil de Asistente de Ventas y Control de Inventario',
    category: 'Mobile App',
    categoryEs: 'Aplicación Móvil',
    description: 'Developing a comprehensive mobile app that empowers salespeople and plant workers to access real-time stock information and streamline inventory management processes.',
    descriptionEs: 'Desarrollo de una aplicación móvil integral que permite a los vendedores y trabajadores de planta acceder a información de stock en tiempo real.',
    tags: ['UX Research', 'Inventory Management', 'Mobile App', 'User Testing'],
    emoji: '📦',
    role: 'UX Researcher & Designer',
    duration: '4 months',
    tools: ['User Interviews', 'Wireframing', 'Prototyping', 'User Testing'],
    challenge: 'The client needed a comprehensive sales and inventory assistant that would empower salespeople and plant workers to access real-time stock information, seamlessly assist clients throughout the warehouse, and streamline inventory management processes.',
    challengeEs: 'El cliente necesitaba un asistente integral de ventas e inventario que permitiera a los vendedores y trabajadores de planta acceder a información de stock en tiempo real.',
    process: {
      research: 'Through on-site research and observation of warehouse workers across 35 stores, I identified numerous pain points in their workflows, validating the initial hypotheses raised in the business requirements.',
      researchEs: 'A través de investigación en el sitio y observación de trabajadores de almacén en 35 tiendas, identifiqué numerosos puntos problemáticos en sus flujos de trabajo.',
      ideation: 'After thoroughly analyzing the project, we crafted a comprehensive work schedule encompassing the project\'s entire scope, divided into distinct stages.',
      ideationEs: 'Después de analizar exhaustivamente el proyecto, elaboramos un cronograma de trabajo integral que abarcaba todo el alcance del proyecto.',
      wireframes: 'I employed a design thinking approach, generating a multitude of potential solutions and meticulously testing the most promising ones.',
      wireframesEs: 'Empleé un enfoque de design thinking, generando una multitud de soluciones potenciales y probando meticulosamente las más prometedoras.',
      testing: 'Focus groups and interviews were conducted to gather valuable insights, ensuring the product aligned with business objectives and user needs.',
      testingEs: 'Se realizaron grupos focales y entrevistas para recopilar información valiosa, asegurando que el producto se alineara con los objetivos del negocio.',
    },
    solution: 'The outcome was an intuitive mobile app that outperformed the existing software and effectively tracked and gathered valuable business information, including real-time stock checks, product information, and client order tracking.',
    solutionEs: 'El resultado fue una aplicación móvil intuitiva que superó al software existente y rastreó y recopiló eficazmente información comercial valiosa.',
    metrics: [
      { value: '40%', label: 'Improvement in Customer Service Efficiency', labelEs: 'Mejora en la Eficiencia del Servicio al Cliente' },
      { value: '35%', label: 'Reduction in Inventory Management Time', labelEs: 'Reducción en el Tiempo de Gestión de Inventario' },
      { value: '25%', label: 'Increase in Sales Conversion Rate', labelEs: 'Aumento en la Tasa de Conversión de Ventas' },
    ],
    learnings: 'This project highlighted the importance of thorough on-site research and direct observation of users in their work environment.',
    learningsEs: 'Este proyecto destacó la importancia de una investigación exhaustiva en el sitio y la observación directa de los usuarios en su entorno de trabajo.',
    next: 'financial-app-redesign'
  },
  {
    id: 'financial-app-redesign',
    title: 'Financial App Redesign',
    titleEs: 'Rediseño de Aplicación Financiera',
    category: 'Mobile App',
    categoryEs: 'Aplicación Móvil',
    description: 'Redesigning a financial management application to improve user experience and increase engagement.',
    descriptionEs: 'Rediseño de una aplicación de gestión financiera para mejorar la experiencia del usuario y aumentar el compromiso.',
    tags: ['UX Design', 'UI Design', 'User Research', 'Fintech'],
    emoji: '💳',
    role: 'Lead UX Designer',
    duration: '3 months',
    tools: ['Figma', 'Miro', 'UserTesting', 'Hotjar'],
    challenge: 'The client\'s financial app had low engagement rates and users reported difficulty navigating through key features.',
    challengeEs: 'La aplicación financiera del cliente tenía bajas tasas de participación y los usuarios informaron dificultades para navegar por las funciones clave.',
    process: {
      research: 'We conducted user interviews with 15 existing users and analyzed app usage data to identify pain points.',
      researchEs: 'Realizamos entrevistas con 15 usuarios existentes y analizamos los datos de uso de la aplicación para identificar puntos problemáticos.',
      ideation: 'Based on research findings, we conducted ideation workshops and created user flows to restructure the app\'s navigation.',
      ideationEs: 'Basados en nuestros hallazgos, realizamos talleres de ideación y creamos flujos de usuario para reestructurar la navegación.',
      wireframes: 'We developed low-fidelity wireframes focusing on simplifying the transaction categorization process.',
      wireframesEs: 'Desarrollamos wireframes de baja fidelidad enfocados en simplificar el proceso de categorización de transacciones.',
      testing: 'We conducted usability testing with 8 participants using interactive prototypes.',
      testingEs: 'Realizamos pruebas de usabilidad con 8 participantes utilizando prototipos interactivos.',
    },
    solution: 'The final design featured a simplified navigation structure, a redesigned transaction categorization system with AI-assisted suggestions, and an intuitive budget setting interface.',
    solutionEs: 'El diseño final presentó una estructura de navegación simplificada y un sistema de categorización de transacciones rediseñado con sugerencias asistidas por IA.',
    metrics: [
      { value: '35%', label: 'Increase in User Engagement', labelEs: 'Aumento en la Participación de Usuarios' },
      { value: '40%', label: 'Decrease in Task Completion Time', labelEs: 'Disminución en el Tiempo de Finalización de Tareas' },
      { value: '40%', label: 'Improvement in User Satisfaction', labelEs: 'Mejora en la Satisfacción del Usuario' },
    ],
    learnings: 'This project taught me the importance of balancing simplicity with functionality in financial applications.',
    learningsEs: 'Este proyecto me enseñó la importancia de equilibrar la simplicidad con la funcionalidad en aplicaciones financieras.',
    next: 'e-commerce-platform'
  },
  {
    id: 'e-commerce-platform',
    title: 'E-commerce Platform Optimization',
    titleEs: 'Optimización de Plataforma de Comercio Electrónico',
    category: 'Web Design',
    categoryEs: 'Diseño Web',
    description: 'Enhancing the user experience of an e-commerce platform to increase conversion rates and customer satisfaction.',
    descriptionEs: 'Mejorando la experiencia del usuario de una plataforma de comercio electrónico para aumentar las tasas de conversión.',
    tags: ['E-commerce', 'Conversion Optimization', 'User Testing', 'Responsive Design'],
    emoji: '🛒',
    role: 'UX Designer & Researcher',
    duration: '4 months',
    tools: ['Sketch', 'InVision', 'Google Analytics', 'Optimizely'],
    challenge: 'The client\'s e-commerce platform was experiencing high cart abandonment rates and users reported confusion during the checkout process.',
    challengeEs: 'La plataforma de comercio electrónico del cliente estaba experimentando altas tasas de abandono del carrito.',
    process: {
      research: 'We analyzed user behavior data and conducted 12 user interviews to identify pain points in the checkout process.',
      researchEs: 'Analizamos datos de comportamiento del usuario y realizamos 12 entrevistas para identificar puntos problemáticos.',
      ideation: 'We developed concepts for improving the checkout flow, including a streamlined single-page checkout.',
      ideationEs: 'Desarrollamos conceptos para mejorar el flujo de pago, incluyendo un proceso simplificado de una sola página.',
      wireframes: 'We created wireframes for the new checkout flow, focusing on reducing the number of steps.',
      wireframesEs: 'Creamos wireframes para el nuevo flujo de pago, enfocándonos en reducir el número de pasos.',
      testing: 'We conducted A/B testing with the new designs against the existing checkout flow.',
      testingEs: 'Realizamos pruebas A/B con los nuevos diseños contra el flujo de pago existente.',
    },
    solution: 'The final solution included a streamlined three-step checkout process, real-time form validation, and multiple payment options clearly presented.',
    solutionEs: 'La solución final incluyó un proceso de pago simplificado de tres pasos y validación de formularios en tiempo real.',
    metrics: [
      { value: '28%', label: 'Decrease in Cart Abandonment', labelEs: 'Disminución en Abandono del Carrito' },
      { value: '15%', label: 'Increase in Conversion Rate', labelEs: 'Aumento en la Tasa de Conversión' },
      { value: '34%', label: 'Improvement in Customer Satisfaction', labelEs: 'Mejora en la Satisfacción del Cliente' },
    ],
    learnings: 'This project reinforced the importance of simplicity and clarity in e-commerce design.',
    learningsEs: 'Este proyecto reforzó la importancia de la simplicidad y la claridad en el diseño de comercio electrónico.',
    next: 'educastic-platform'
  },
  {
    id: 'educastic-platform',
    title: 'Educastic – UX Consultancy for a Virtual Education Platform',
    titleEs: 'Educastic – Consultoría UX para una Plataforma de Educación Virtual',
    category: 'UX Consultancy',
    categoryEs: 'Consultoría UX',
    description: 'Online classrooms reimagined through user-centered design.',
    descriptionEs: 'Aulas virtuales reimaginadas a través del diseño centrado en el usuario.',
    tags: ['Education', 'UX Audit', 'User Research', 'Accessibility'],
    emoji: '🎓',
    role: 'UX Consultant & Designer',
    duration: '3 months',
    tools: ['User Interviews', 'Journey Mapping', 'Wireframing', 'Heuristic Analysis'],
    challenge: 'The platform had been developed rapidly without a UX process, resulting in inconsistent UI patterns, low user engagement, and accessibility gaps.',
    challengeEs: 'La plataforma se había desarrollado rápidamente sin un proceso de UX, resultando en patrones inconsistentes y brechas de accesibilidad.',
    process: {
      research: 'I conducted interviews with key user segments and identified usability pain points through a comprehensive UX audit.',
      researchEs: 'Realicé entrevistas con segmentos clave de usuarios e identifiqué puntos problemáticos a través de una auditoría UX.',
      ideation: 'I prioritized classroom access, communication, and content sharing flows, defining user personas and accessibility needs.',
      ideationEs: 'Prioricé los flujos de acceso al aula, comunicación y compartición de contenido, definiendo personas de usuario.',
      wireframes: 'I created annotated wireframes focused on improving clarity and reducing cognitive load for users.',
      wireframesEs: 'Creé wireframes anotados enfocados en mejorar la claridad y reducir la carga cognitiva para los usuarios.',
      testing: 'I maintained biweekly check-ins with developers to ensure feasibility and monitored UX improvements post-implementation.',
      testingEs: 'Mantuve reuniones quincenales con los desarrolladores para garantizar la viabilidad y monitoreé las mejoras post-implementación.',
    },
    solution: 'I introduced interface consistency through a basic style guide and streamlined the platform navigation to make it more intuitive.',
    solutionEs: 'Introduje consistencia en la interfaz a través de una guía de estilo básica y simplifiqué la navegación de la plataforma.',
    metrics: [
      { value: '42%', label: 'Increase in User Engagement', labelEs: 'Aumento en la Participación de Usuarios' },
      { value: '35%', label: 'Reduction in Support Tickets', labelEs: 'Reducción en Tickets de Soporte' },
      { value: '28%', label: 'Improvement in Task Completion Rate', labelEs: 'Mejora en la Tasa de Finalización de Tareas' },
    ],
    learnings: 'Designing for education means designing for inclusivity. Balancing teacher workflows with student experience requires empathy and adaptability.',
    learningsEs: 'Diseñar para la educación significa diseñar para la inclusión. Equilibrar los flujos de trabajo de los profesores con la experiencia de los estudiantes requiere empatía.',
    next: 'digital-wallet-platform'
  },
  {
    id: 'digital-wallet-platform',
    title: 'UX Optimization for a Digital Wallet Platform',
    titleEs: 'Optimización UX para una Plataforma de Billetera Digital',
    category: 'Fintech',
    categoryEs: 'Fintech',
    description: 'Enhancing secure digital payments with user-centered design.',
    descriptionEs: 'Mejorando los pagos digitales seguros con diseño centrado en el usuario.',
    tags: ['Digital Payments', 'UI Design', 'User Experience', 'Mobile App'],
    emoji: '💰',
    role: 'UI Designer in Product Team',
    duration: 'Ongoing since 2019',
    tools: ['Figma', 'Adobe Illustrator', 'Prototyping Tools', 'Analytics Platforms'],
    challenge: 'Users encountered challenges navigating the app, specifically a fragmented visual hierarchy and interaction flows that hindered task completion.',
    challengeEs: 'Los usuarios encontraron desafíos al navegar por la aplicación, específicamente una jerarquía visual fragmentada.',
    process: {
      research: 'I reviewed user feedback and conducted heuristic evaluations to identify pain points, mapping key user journeys.',
      researchEs: 'Revisé los comentarios de los usuarios y realicé evaluaciones heurísticas para identificar puntos problemáticos.',
      ideation: 'I redesigned navigation structures and interaction cues to streamline workflows and updated the visual design system.',
      ideationEs: 'Rediseñé las estructuras de navegación y las señales de interacción para optimizar los flujos de trabajo.',
      wireframes: 'I developed interactive prototypes for usability testing, gathering actionable insights for iterative refinements.',
      wireframesEs: 'Desarrollé prototipos interactivos para pruebas de usabilidad, recopilando información procesable.',
      testing: 'I worked with cross-functional teams to ensure technical feasibility and deployed incremental changes while monitoring metrics.',
      testingEs: 'Trabajé con equipos multifuncionales para garantizar la viabilidad técnica e implementé cambios incrementales.',
    },
    solution: 'The solution was a more intuitive and secure interface, leading to smoother user journeys during financial transactions.',
    solutionEs: 'La solución fue una interfaz más intuitiva y segura, lo que llevó a viajes de usuario más fluidos durante las transacciones financieras.',
    metrics: [
      { value: '38%', label: 'Increase in User Engagement', labelEs: 'Aumento en la Participación de Usuarios' },
      { value: '45%', label: 'Reduction in Support Tickets', labelEs: 'Reducción en Tickets de Soporte' },
      { value: '32%', label: 'Improvement in Transaction Completion Rate', labelEs: 'Mejora en la Tasa de Finalización de Transacciones' },
    ],
    learnings: 'Designing for digital financial services requires a balanced focus on security, clarity, and ease of use.',
    learningsEs: 'Diseñar para servicios financieros digitales requiere un enfoque equilibrado en seguridad, claridad y facilidad de uso.',
    next: 'sales-inventory-assistant'
  }
];
